### ISSUE TITLE
Support for additional picture properties

### ISSUE THREAD

**Issue by vikramsvang** [k0w4lk/gulp-html-img-wrapper#1]
Hi,

I have 100s of img tags in my HTML files. I am converting the project using gulp and following this article to use responsive images as per media type, width etc.

https://dev.to/khalyomede/create-responsive-images-with-gulp-sharp-responsive-9c6

I found your plugin and it is promising to use but need support for the following picture syntax as per the above article.

```
<picture>
  <!-- avif -->
  <source srcset="/img/lion-sm.avif" media="(max-width: 640px)" type="image/avif" />
  <source srcset="/img/lion-md.avif" media="(max-width: 768px)" type="image/avif" />
  <source srcset="/img/lion-lg.avif" media="(max-width: 1024px)" type="image/avif" />
  <!-- webp -->
  <source srcset="/img/lion-sm.webp" media="(max-width: 640px)" type="image/webp" />
  <source srcset="/img/lion-md.webp" media="(max-width: 768px)" type="image/webp" />
  <source srcset="/img/lion-lg.webp" media="(max-width: 1024px)" type="image/webp" />
  <!-- jpeg -->
  <source srcset="/img/lion-sm.jpeg" media="(max-width: 640px)" type="image/jpeg" />
  <source srcset="/img/lion-md.jpeg" media="(max-width: 768px)" type="image/jpeg" />
  <source srcset="/img/lion-lg.jpeg" media="(max-width: 1024px)" type="image/jpeg" />
  <!-- original -->
  <img src="/img/lion.jpeg" class="img-responsive" alt="A lion in the jungle." />
</picture>
```

So, if my HTML has the original syntax `<img src="/img/lion.jpeg" class="img-responsive" alt="A lion in the jungle." />` then it would be very useful if your plugin can generate the above syntax. 

Is it possible for you to enhance your plugin?

Thank YOU

**Comment by k0w4lk** [comment]
Hello! Thanks for your suggestion. That's a really cool idea, I'm interested in it. I'll try to update my plugin in some time.

**Comment by k0w4lk** [comment]
> Is it possible for you to enhance your plugin?

Done in v4.0.0, please check it and reply here if it's all OK.
